library(dplyr)
library(ggplot2)

# base of the tree: adding green lines based on the points generated by a separate python script
green_linepts <- read.csv("full_data.csv") %>% 
  select(-X)

full_christmas_tree <- ggplot(green_linepts, aes(y = y)) +   
  geom_line(aes(x = x1), color = "green") + 
  geom_line(aes(x = x2), color = "green") + 
  geom_line(aes(x = x3), color = "green") + 
  geom_line(aes(x = x4), color = "green") + 
  geom_line(aes(x = x5), color = "green") + 
  geom_line(aes(x = x6), color = "green") + 
  geom_line(aes(x = x7), color = "green") + 
  geom_line(aes(x = x8), color = "green") + 
  geom_line(aes(x = x9), color = "green") + 
  geom_line(aes(x = x10), color = "green") +
  geom_line(aes(x = x11), color = "green") + 
  geom_line(aes(x = x12), color = "green") + 
  geom_line(aes(x = x13), color = "green") + 
  geom_line(aes(x = x14), color = "green") + 
  geom_line(aes(x = x15), color = "green") + 
  geom_line(aes(x = x16), color = "green") + 
  geom_line(aes(x = x17), color = "green") + 
  geom_line(aes(x = x18), color = "green") + 
  geom_line(aes(x = x19), color = "green") + 
  geom_line(aes(x = x20), color = "green") +
  geom_line(aes(x = x21), color = "green") + 
  geom_line(aes(x = x22), color = "green") + 
  geom_line(aes(x = x23), color = "green") + 
  geom_line(aes(x = x24), color = "green") + 
  geom_line(aes(x = x25), color = "green") + 
  geom_line(aes(x = x26), color = "green") + 
  geom_line(aes(x = x27), color = "green") + 
  geom_line(aes(x = x28), color = "green") + 
  geom_line(aes(x = x29), color = "green") + 
  geom_line(aes(x = x30), color = "green") +
  geom_line(aes(x = x31), color = "green") + 
  geom_line(aes(x = x32), color = "green") + 
  geom_line(aes(x = x33), color = "green") + 
  geom_line(aes(x = x34), color = "green") + 
  geom_line(aes(x = x35), color = "green") + 
  geom_line(aes(x = x36), color = "green") + 
  geom_line(aes(x = x37), color = "green") + 
  geom_line(aes(x = x38), color = "green") + 
  geom_line(aes(x = x39), color = "green") + 
  geom_line(aes(x = x40), color = "green") +
  geom_line(aes(x = x41), color = "green") + 
  geom_line(aes(x = x42), color = "green") + 
  geom_line(aes(x = x43), color = "green") + 
  geom_line(aes(x = x44), color = "green") + 
  geom_line(aes(x = x45), color = "green") + 
  geom_line(aes(x = x46), color = "green") + 
  geom_line(aes(x = x47), color = "green") + 
  geom_line(aes(x = x48), color = "green") + 
  geom_line(aes(x = x49), color = "green") + 
  geom_line(aes(x = x50), color = "green") +
  xlim(-2,2) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "navyblue",
                                    colour = "navyblue",
                                    size = 0.5, linetype = "solid"),
    axis.text.x = element_blank(), 
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(), 
    axis.ticks.y = element_blank()
  ) + 
  labs(
    x = "",
    y = ""
  )

# adding tree stump
stump_data <- data.frame(
  x = c(0),
  y = c(-0.2)
)

full_christmas_tree <- full_christmas_tree +
  geom_col(data = stump_data, aes(x = x, y = y), position = "stack", fill = "#57280d", width = 0.5)

# adding star on top
star_points <- data.frame(
  x = c(0), 
  y = c(4)
)

full_christmas_tree <- full_christmas_tree +
  geom_point(data = star_points, aes(x = x, y = y), shape = 17, color = "yellow", size = 10) +
  geom_point(data = star_points, aes(x = x, y = y), shape = 25, fill = "yellow", color = "yellow", size = 10)

# adding different kinds of snowflakes
small_snow_points <- data.frame(
  x = c(-1.5, -1, 0.75, 1.75, 0.6, -1),
  y = c(3.5, 2, 4, 1, 2.9, 4)
)

medium_snow_points <- data.frame(
  x = c(-2, 1.9, 1, -0.75, -1.3, 1.2),
  y = c(1, 3.8, 2, 3, 0.5, 3.3)
)

large_snow_points <- data.frame(
  x = c(-1.75, -1.4, 1.9, 1.1),
  y = c(2.5, 1.2, 2.3, 0.8)
)

full_christmas_tree <- full_christmas_tree +
  geom_point(data = small_snow_points, aes(x = x, y = y), shape = 8, color = "white", size = 4) +
  geom_point(data = medium_snow_points, aes(x = x, y = y), shape = 8, color = "white", size = 6) +
  geom_point(data = large_snow_points, aes(x = x, y = y), shape = 8, color = "white", size = 8)

# adding decorative baubles
bauble_points <- data.frame(
  x = c(0.2, 0.9, -0.3, 0.1, -0.7, 0.5, 0, -0.2, -0.27, -0.08, 0, -0.8),
  y = c(3, 0.2, 0.3, 0.5, 1, 1.5, 2, 1.8, 2.7, 3.5, 1, 0.1)
)

full_christmas_tree <- full_christmas_tree +
  geom_point(data = bauble_points, aes(x = x, y = y), shape = 19, color = "red", size = 5)

full_christmas_tree
ggsave(filename="christmas_tree.png")